from distutils.core import setup

setup(name='pyDAG',
      version='1.4',
      author='Dave Gutz',
      author_email='dave.gutz@ge.com',
      url='http://www.google.com',
      description='Dave Gutz Python Utilities',
      long_description=None,
      license=None,
      platforms='OS Independent',
      classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Console',
        'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
        'Intended Audience :: Developers',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: Utilities'
      ],
      package_dir={'pyDAG': 'pyDAG'},
      package_data={'pyDAG':
             ['Apps/GE38_EngineDataReduction/c005r9951.eu',
              'Apps/GE38_RotorDynamicModel/README.TXT',
              'Apps/GE38_RotorDynamicModel/rotorCurves.txt',
              'Apps/GE38_RotorDynamicModel/rotorCurves.txtOld',
              'Apps/GE38_RotorDynamicModel/rotorModel.csv',
              'Apps/GE38_RotorDynamicModel/rotorModel.dat',
              'Apps/GE38_RotorDynamicModel/rotorModel.map',
              'Apps/GE38_RotorDynamicModel/rotorModel.xls',
              'Apps/GE38_RotorDynamicModel/rotorModel006.xls',
              'Apps/GE38_RotorDynamicModel/rotorModel010.xls',
              'Apps/GE38_RotorDynamicModel/rotorModel012.xls',
              'Apps/GE38_RotorDynamicModel/rotorModel_2damstep.csv',
              'Apps/GE38_RotorDynamicModel/rotorModel_2damstep.xls',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081106.csv',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081106.xml',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081121',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081121.csv',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081121.xml',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081216.csv',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_BookAndPage_20081216.xml',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_rev0.cfg',
              'Apps/GE38_WetRigXML_ConfigFiles/GE38_ARINC_rev0.txt',
              'Apps/GE38_WetRigXML_ConfigFiles/README.txt',
              'Apps/GE38_WetRigXML_ConfigFiles/cvs2BPxml.zap',
              'Apps/GE38_WetRigXML_ConfigFiles/fts_rfm_import.xml',
              'Apps/GE38_WetRigXML_ConfigFiles/python.gpl',
              'Apps/GE38_WetRigXML_ConfigFiles/rm_import_erros (2).doc',
              'Apps/GE38_WetRigXML_ConfigFiles/rm_import_erros.doc',
              'Apps/genGorilla/README.TXT',
              'Apps/genGorilla/airstart.mtc',
              'Apps/genGorilla/g1000.def',
              'Apps/genGorilla/g1000.int',
              'Apps/genGorilla/g110.def',
              'Apps/genGorilla/g110.int',
              'Apps/genGorilla/g110.mtp',
              'Apps/genGorilla/g110.scd',
              'Apps/genGorilla/g111.def',
              'Apps/genGorilla/g111.int',
              'Apps/genGorilla/g111.mtp',
              'Apps/genGorilla/g111.scd',
              'Apps/watermark/README.txt',
              'Apps/watermark/watermarkKPE.png',
              'Apps/watermark/watermarkKPEr.png',
              'Apps/makeBsrc/ge3000v210.mbs',
              'Apps/copire/Export2.TXT']},
      scripts=['pyDAG/Apps/copire/copire',
               'pyDAG/Apps/GE38_EngineDataReduction/eu2csv.py',
               'pyDAG/Apps/GE38_RotorDynamicModel/rotorModel.py',
               'pyDAG/Apps/GE38_WetRigXML_ConfigFiles/csv2BPxml.py',
               'pyDAG/Apps/makeCMD/makeCMD',
               'pyDAG/Apps/makeCMD/makeTBLADJ',
               'pyDAG/Apps/makeCMD/map2tbl',
               'pyDAG/Apps/makeCMD/ins2adj',
               'pyDAG/Apps/makeCMD/sar2trim',
               'pyDAG/Apps/genGorilla/genGorilla.py',
               'pyDAG/Apps/makeCMD/makeCMD.py',
               'pyDAG/Apps/makeCMD/makeTBLADJ.py',
               'pyDAG/Apps/makeCMD/ctblmkr_GEneric.c',
               'pyDAG/Apps/makeCMD/ctblmkr_GEneric_win.exe',
               'pyDAG/Apps/watermark/watermark.py',
               'pyDAG/Apps/makeBsrc/MakeBsrc.py',
               'pyDAG/Apps/pyReplace',
               'pyDAG/System/myReplace.py',
               'pyDAG/Apps/copire/copire',
               'pyDAG/Apps/copire/copire.py'],
      packages=['pyDAG', 'pyDAG.TextProcessing', 'pyDAG.Dynamics', 'pyDAG.Tables', 'pyDAG.System', 'pyDAG.Tkinter']
)
