#  from distutils.core import setup
import distutils.core as duc

duc.setup(name='pyDAG',
          version='1.4',
          author='Dave Gutz',
          author_email='dave.gutz@ge.com',
          url='http://www.google.com',
          description='Dave Gutz Python Utilities',
          long_description=None,
          license=None,
          platforms='OS Independent',
          classifiers=[
              'Development Status :: 4 - Beta',
              'Environment :: Console',
              'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
              'Intended Audience :: Developers',
              'Operating System :: OS Independent',
              'Programming Language :: Python',
              'Topic :: Utilities'
          ],
          package_dir={'pyDAG': 'pyDAG'},
          package_data={'pyDAG':
                        ['Apps/EngineDataReduction/c005r9951.eu',
                         'Apps/RotorDynamicModel/README.TXT',
                         'Apps/RotorDynamicModel/rotorCurves.txt',
                         'Apps/RotorDynamicModel/rotorCurves.txtOld',
                         'Apps/RotorDynamicModel/rotorModel.csv',
                         'Apps/RotorDynamicModel/rotorModel.dat',
                         'Apps/RotorDynamicModel/rotorModel.map',
                         'Apps/RotorDynamicModel/rotorModel.xls',
                         'Apps/RotorDynamicModel/rotorModel006.xls',
                         'Apps/RotorDynamicModel/rotorModel010.xls',
                         'Apps/RotorDynamicModel/rotorModel012.xls',
                         'Apps/RotorDynamicModel/rotorModel_2damstep.csv',
                         'Apps/RotorDynamicModel/rotorModel_2damstep.xls',
                         'Apps/genGorilla/README.TXT',
                         'Apps/genGorilla/airstart.mtc',
                         'Apps/genGorilla/g1000.def',
                         'Apps/genGorilla/g1000.int',
                         'Apps/genGorilla/g110.def',
                         'Apps/genGorilla/g110.int',
                         'Apps/genGorilla/g110.mtp',
                         'Apps/genGorilla/g110.scd',
                         'Apps/genGorilla/g111.def',
                         'Apps/genGorilla/g111.int',
                         'Apps/genGorilla/g111.mtp',
                         'Apps/genGorilla/g111.scd',
                         'Apps/genGorilla/genGorilla.dic',
                         'Apps/makeCMD/makeCMD.dic',
                         'Apps/RotorDynamicModel/rotorModel.dic',
                         'Apps/watermark/README.txt',
                         'Apps/watermark/watermarkKPE.png',
                         'Apps/watermark/watermarkKPEr.png',
                         'Apps/watermark/Figure_1.jpg',
                         'Apps/watermark/Figure_1.png',
                         'Apps/watermark/wFigure_1.jpg',
                         'Apps/watermark/watermark.dic',
                         'pyDAG.dic',
                         'System/tests/MANIFEST.in',
                         'System/tests/mySystem.dic',
                         'System/tests/pyDAG.dic']},
          scripts=['pyDAG/Apps/EngineDataReduction/eu2csv.py',
                   'pyDAG/Apps/RotorDynamicModel/rotorModel.py',
                   'pyDAG/Apps/makeCMD/makeCMD',
                   'pyDAG/Apps/makeCMD/makeTBLADJ',
                   'pyDAG/Apps/makeCMD/map2tbl',
                   'pyDAG/Apps/makeCMD/ins2adj',
                   'pyDAG/Apps/makeCMD/sar2trim',
                   'pyDAG/Apps/genGorilla/genGorilla.py',
                   'pyDAG/Apps/makeCMD/makeCMD.py',
                   'pyDAG/Apps/makeCMD/makeTBLADJ.py',
                   'pyDAG/Apps/makeCMD/ctblmkr_GEneric.c',
                   'pyDAG/Apps/makeCMD/ctblmkr_GEneric_win.exe',
                   'pyDAG/Apps/watermark/watermark.py',
                   'pyDAG/Apps/pyReplace',
                   'pyDAG/System/myReplace.py'],
          packages=['pyDAG', 'pyDAG.TextProcessing', 'pyDAG.Dynamics', 'pyDAG.Tables', 'pyDAG.System', 'pyDAG.Tkinter'],
          requires=['Pillow']
          )
